AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  teams-workflow-webhook-proxy-for-github-app

Globals:
  Function:
    Timeout: 3

Resources:
  ForGitHubFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: for-github-function
      CodeUri: teams_workflow_webhook_proxy_for_github/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
        - x86_64
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
      Layers:
        - arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension:23
      Environment:
        Variables:
          SSM_PARAMETER_PATH: "/teams/tech-blog-pr-notification-channel/workflow/webhook-url"
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /webhook
            Method: post
